export const Projects = [
    {
        id: 1,
        title: "Title",
        category: "photos",
        img: require("../../assets/img/projects/8mart.png"),
        technologies: "Photoshop",
    },
    {
        id: 2,
        title: "Title",
        category: "photos",
        img: require("../../assets/img/projects/14fevral.png"),
        technologies: "Photoshop",
    },
    {
        id: 3,
        title: "Title",
        category: "photos",
        img: require("../../assets/img/projects/30yanvar.png"),
        technologies: "Photoshop",
    },
    {
        id: 4,
        title: "Title",
        category: "photos",
        img: require("../../assets/img/projects/123x-100.jpg"),
        technologies: "Photoshop",
    },
    {
        id: 5,
        title: "Title",
        category: "photos",
        img: require("../../assets/img/projects/beforeafter.png"),
        technologies: "Photoshop",
    },
    {
        id: 6,
        title: "Title",
        category: "photos",
        img: require("../../assets/img/projects/flat SEVİNC.jpg"),
        technologies: "Photoshop",
    },
    // {
    //     id: 7,
    //     title: "Title",
    //     category: "gif",
    //     img: require("../../assets/img/projects/hsevinc.gif"),
    //     technologies: "Photoshop",
    // },
    {
        id: 8,
        title: "Title",
        category: "photos",
        img: require("../../assets/img/projects/POSTER.png"),
        technologies: "Photoshop",
    },
    {
        id: 9,
        title: "Title",
        category: "photos",
        img: require("../../assets/img/projects/SEVINC BR.png"),
        technologies: "Photoshop",
    },
    {
        id: 10,
        title: "Title",
        category: "photos",
        img: require("../../assets/img/projects/Sevinc Hasanova.png"),
        technologies: "Photoshop",
    },
    {
        id: 11,
        title: "Title",
        category: "photos",
        img: require("../../assets/img/projects/Sevinc2.png"),
        technologies: "Photoshop",
    },
    {
        id: 12,
        title: "Title",
        category: "photos",
        img: require("../../assets/img/projects/Sevinc3.png"),
        technologies: "Photoshop",
    },
    {
        id: 14,
        title: "Title",
        category: "photos",
        img: require("../../assets/img/projects/tuk efekti.jpg"),
        technologies: "Photoshop",
    },
    {
        id: 15,
        title: "Title",
        category: "photos",
        img: require("../../assets/img/projects/Untitled-1.png"),
        technologies: "Photoshop",
    },
    {
        id: 16,
        title: "Title",
        category: "photos",
        img: require("../../assets/img/projects/Untitled-6.jpg"),
        technologies: "Photoshop",
    },
    {
        id: 17,
        title: "Title",
        category: "photos",
        img: require("../../assets/img/projects/yeni il.png"),
        technologies: "Photoshop",
    },
];